ccct2019/Controllers/NganchanGiaitoaController.cs
using ccct2019.Data;
using ccct2019.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ccct2019.Controllers
{
    public class NganchanGiaitoaController : Controller
    {
        // GET: NganchanGiaitoa

        ConnectDB cnn = new ConnectDB();

        [AuthorizeBussiness]
        public ActionResult Index()
        {
            int numberNcgt = cnn.NganchanGiaitoa.Where(a => a.IsActive.Equals(1) && a.Demncgt.Equals(null)).Count();
            ViewBag.numberNcgt = numberNcgt;
            
            return View();
        }

        public ActionResult ViewNCGT()
        {
            return View();
        }

        [AuthorizeBussiness]
        public PartialViewResult Search(string search = "", int page = 1)
        {
            var query = from p in cnn.NganchanGiaitoa
                        where p.SoGCN.Contains(search) && p.IsActive.Equals(1) || p.Noicap.Contains(search) && p.IsActive.Equals(1)
                        orderby p.CreateDate descending
                        select p;
            List<NganchanGiaitoa> listncgt = query.ToList();
            IPagedList<NganchanGiaitoa> listPagedNcgt = query.ToPagedList(page, 7);
            return PartialView("_ListNcgt", listPagedNcgt);
        }
        [AuthorizeBussiness]
        public PartialViewResult SearchMod(string search = "", int page = 1)
        {
            var query = from p in cnn.NganchanGiaitoa
                        where p.SoGCN.Contains(search) && p.IsActive.Equals(1) || p.Noicap.Contains(search) && p.IsActive.Equals(1)
                        orderby p.CreateDate descending
                        select p;
            List<NganchanGiaitoa> listncgt = query.ToList();
            IPagedList<NganchanGiaitoa> listPagedNcgt = query.ToPagedList(page, 7);
            return PartialView("_ListNcgtMod", listPagedNcgt);
        }




        //Upload file

        public string UploadFile(HttpPostedFileBase file)
        {
            //xử lý upload
            // Get random file name.
            //
            string msg = "";
            string random = Path.GetRandomFileName();

            file.SaveAs(Server.MapPath("~/Content/uploadfile/file/" + random + file.FileName));
            msg = random + file.FileName;
            return msg;

        }

        //thêm ncgt
        public int Add(int UserID, string SoGCN, string noicap, DateTime ngaycap, string hoten, string diachi, string thuadat, string bandoso,
            string diachithuadat, string dientich, string sudungchung, string mucdichsudung, string sudungrieng, string thoihansudung,
            string nguongoc, int loaivb, string sokyhieu, DateTime ngayvb, string noigui, string lydo, string filedinhkem)
        {
            try
            {

                NganchanGiaitoa ncgt = new NganchanGiaitoa();
                ncgt.SoGCN = SoGCN;
                ncgt.Noicap = noicap;
                //string thang = Convert.ToString(ngaycap.Month);
                //string nam = Convert.ToString(ngaycap.Year);
                //string dateformart = (ngay + "-" + thang + "-" + nam);
                ncgt.Ngaycap = ngaycap;
                ncgt.Chusohuu = hoten;
                ncgt.Diachichusohuu = diachi;
                ncgt.Thuadatso = thuadat;
                ncgt.Bandoso = bandoso;
                ncgt.Diachithuadat = diachithuadat;
                ncgt.Dientich = dientich;
                ncgt.Sudungchung = sudungchung;
                ncgt.Sudungrieng = sudungrieng;
                ncgt.Mucdichsudung = mucdichsudung;
                ncgt.Thoihansudung = thoihansudung;
                ncgt.Nguongoc = nguongoc;
                ncgt.LoaiVB = loaivb;
                ncgt.Sokyhieu = sokyhieu;
                //string ngayb = Convert.ToString(ngayvb.Day);
                //string thangb = Convert.ToString(ngayvb.Month);
                //string namb = Convert.ToString(ngayvb.Year);
                //string dateformartvb = (ngayb + "-" + thangb + "-" + namb);
                ncgt.NgayVB = ngayvb;
                ncgt.Noigui = noigui;
                ncgt.Lydo = lydo;
                ncgt.Filedinhkem = ("/Content/uploadfile/file/" + filedinhkem);
                ncgt.UserID = UserID;
                
                ncgt.CreateDate = DateTime.Now;
                ncgt.IsActive = 1;
                //Luu Pack vao DB
                cnn.NganchanGiaitoa.Add(ncgt);
                cnn.SaveChanges();
                return 1;
                //
            }
            catch
            {
                return 0;
            }

        }

        //Xem ncgt
        public PartialViewResult GetDetail(int ncgtID)
        {
            var query = from i in cnn.NganchanGiaitoa
                        where i.IsActive.Equals(1) && i.ID.Equals(ncgtID)
                        select (i);
            NganchanGiaitoa u = query.FirstOrDefault();
            NganchanGiaitoa Congdem = cnn.NganchanGiaitoa.Find(ncgtID);
            Congdem.Demncgt = 1;
            cnn.SaveChanges();

            return PartialView("_Xemncgt", u);
        }

        //Xem ncgt
        public PartialViewResult GetDetailMod(int ncgtID)
        {
            var query = from i in cnn.NganchanGiaitoa
                        where i.IsActive.Equals(1) && i.ID.Equals(ncgtID)
                        select (i);
            NganchanGiaitoa u = query.FirstOrDefault();
            NganchanGiaitoa Congdem = cnn.NganchanGiaitoa.Find(ncgtID);
            Congdem.Demncgt = 1;
            cnn.SaveChanges();

            return PartialView("_XemncgtMod", u);
        }

        //get id ncgt
        public PartialViewResult GetUpdate(int sncgtID)
        {
            var query = from i in cnn.NganchanGiaitoa
                        where i.IsActive.Equals(1) && i.ID.Equals(sncgtID)
                        select (i);
            NganchanGiaitoa u = query.FirstOrDefault();

            return PartialView("_Suancgt", u);
        }

        //Sửa ngăn chặn giải tỏa
        public int Edit(int NcgtID, int UserID, string SoGCN, string noicap, DateTime ngaycap, string hoten, string diachi, string thuadat, string bandoso,
            string diachithuadat, string dientich, string sudungchung, string mucdichsudung, string sudungrieng, string thoihansudung,
            string nguongoc, int loaivb, string sokyhieu, DateTime ngayvb, string noigui, string lydo, string filedinhkem)
        {
            try
            {
                NganchanGiaitoa update = cnn.NganchanGiaitoa.Find(NcgtID);

                update.SoGCN = SoGCN;
                update.Noicap = noicap;
                update.Ngaycap = ngaycap;
                update.Chusohuu = hoten;
                update.Diachichusohuu = diachi;
                update.Thuadatso = thuadat;
                update.Bandoso = bandoso;
                update.Diachithuadat = diachithuadat;
                update.Dientich = dientich;
                update.Sudungchung = sudungchung;
                update.Sudungrieng = sudungrieng;
                update.Mucdichsudung = mucdichsudung;
                update.Thoihansudung = thoihansudung;
                update.Nguongoc = nguongoc;
                update.LoaiVB = loaivb;
                update.Sokyhieu = sokyhieu;
                update.NgayVB = ngayvb;
                update.Noigui = noigui;
                update.Lydo = lydo;
                string filedinhkemmoi = ("/Content/uploadfile/file/" + filedinhkem);
                string filedinhkemcu = update.Filedinhkem;
                //so sanh file dinh kem
                if (filedinhkem == filedinhkemcu)
                {
                    update.Filedinhkem = filedinhkemcu;
                }
                else
                {
                    update.Filedinhkem = filedinhkemmoi;
                }

                update.UserID = UserID;
                update.CreateDate = DateTime.Now;
                update.IsActive = 1;
                //Luu Pack vao DB       
                cnn.SaveChanges();
                return 1;

            }
            catch
            {
                return 0;
            }

        }

        //get id ncgt
        public PartialViewResult GetDelete(int ncgtID)
        {
            var query = from i in cnn.NganchanGiaitoa
                        where i.IsActive.Equals(1) && i.ID.Equals(ncgtID)
                        select (i);
            NganchanGiaitoa u = query.FirstOrDefault();

            return PartialView("_Xoancgt", u);
        }

        // Xóa ncgt
        public int Delete(int ID)
        {
            try
            {
                NganchanGiaitoa delete = cnn.NganchanGiaitoa.Find(ID);
                delete.CreateDate = DateTime.Now;
                delete.IsActive = 0;
                //Luu Pack vao DB       
                cnn.SaveChanges();
                return 1;

            }
            catch
            {
                return 0;
            }

        }

        //set time out
        public EmptyResult Alive()
        {
            return new EmptyResult();
        }
    }


}

ccct2019/Views/NganchanGiaitoa/ViewNCGT.cshtml
@{
    ViewBag.Title = "ViewNCGT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row mt-2">
    <div class="col-md-12">
        <div class="card card-default">
            <div class="card-header bg-gradient-primary">
                <div class="card-tools">
                    <div class="input-group input-group-sm">
                        <input type="text" id="searchncgtMod" class="form-control" placeholder="Tìm kiếm">
                        <div class="input-group-append">
                            <button class="btn btn-primary" onclick="searchNganchangiaitoaMod();">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <h3 class="card-title">
                    <i class="fas fa-exclamation-triangle"></i>
                    Xem ngăn chặn - Giải tỏa
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <span class="mt-2" id="tblncgtMod">
                    @{Html.RenderAction("SearchMod", "NganchanGiaitoa", new { search = "", Page = 1 });}
                </span>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>
<div id="XemncgtMod"></div>

ccct2019/Views/NganchanGiaitoa/_ListNcgt.cshtml
@model IPagedList<NganchanGiaitoa>
@using ccct2019.Data
@using PagedList
@using PagedList.Mvc

<table class="table table-bordered table-responsive table-hover d-md-table table-head-fixed" style="overflow-x: scroll;">
    <thead class="text-dark" style="font-size:12px; font-family: Tahoma;">
        <tr class="text-center m-auto" style="z-index:9999999999; ">
            <th class="text-center text-white" style="width:3%; background-color:Highlight !important;">TT</th>
            <th class="text-center text-white" style="width:5%; background-color:Highlight !important;">SỐ GCN</th>
            <th class="text-center text-white" style="width:6%; background-color:Highlight !important;">NGÀY CẤP</th>
            <th class="text-center text-white" style="width:14%; background-color:Highlight !important;">NƠI CẤP</th>
            <th class="text-center text-white" style="width:10%; background-color:Highlight !important;">CHỦ SỞ HỮU</th>
            <th class="text-center text-white" style="width:6%; background-color:Highlight !important;">NGÀY VB</th>
            <th class="text-center text-white" style="width:47%; background-color:Highlight !important;">THÔNG TIN THỬA ĐẤT</th>
            <th class="text-center text-white" style="width:9%; background-color:Highlight !important;">
                <i class="fa fa-cogs"></i>
            </th>
        </tr>

    </thead>
    <tbody class="" style="font-size:14px; ">
        @{
            int stt = 0;
            if (Model.Count() > 0)
            {
                foreach (var nganchangiaitoa in Model.OrderByDescending(x => x.CreateDate))
                {
                    stt++;
                    <tr ondblclick="btnGetXemncgtID(@nganchangiaitoa.ID);" class="">
                        <th style="width:3%">@stt</th>
                        <td style="width:5%">@nganchangiaitoa.SoGCN</td>
                        <td style="width:6%">@(nganchangiaitoa.Ngaycap?.ToString("dd/MM/yyyy"))</td>
                        <td style="width:14%">@nganchangiaitoa.Noicap</td>
                        <td style="width:10%">
                            @nganchangiaitoa.Chusohuu

                        </td>

                        <td style="width:6%">@(nganchangiaitoa.NgayVB?.ToString("dd/MM/yyyy"))</td>
                        <td style="width:47%">
                            @*<div class="row">
                                    <div class="col-2 border-right"><b class="text-primary">Thửa đất số:</b> <b class="text-danger">@nganchangiaitoa.Thuadatso</b></div>
                                    <div class="col-2 border-right"><b class="text-primary">Bản đồ số:</b> <b class="text-danger">@nganchangiaitoa.Bandoso</b></div>
                                    <div class="col-5 border-right"><b class="text-primary">Địa chỉ:</b> <span class="">@nganchangiaitoa.Diachithuadat</span></div>
                                    <div class="col-3">
                                        Loại: @{
                                            if (nganchangiaitoa.LoaiVB.Equals(1))
                                            {
                                                <b style="color:red;"><i class="fa fa-stop-circle"></i> Ngăn chặn</b>
                                            }
                                            else
                                            {
                                                <b style="color:green;"><i class="fa fa-undo"></i> Giải tỏa</b>
                                            }
                                        }
                                    </div>
                                </div>*@
                            <table class="table table-condensed mb-0">
                                <thead>
                                    <tr class="text-sm-center bg-info">
                                        <td style="width:25%">Thửa đất</td>
                                        <td style="width:20%">Bản đồ</td>
                                        <td style="width:45%">Địa chỉ</td>
                                        <td style="width:10%">Loại</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="text-sm-center" style="font-size:12px;">
                                        <td style="width:15%"><b class="text-danger">@nganchangiaitoa.Thuadatso</b></td>
                                        <td style="width:10%"><b class="text-danger">@nganchangiaitoa.Bandoso</b></td>
                                        <td style="width:55%"><span>@nganchangiaitoa.Diachithuadat</span></td>
                                        <td style="width:20%">
                                            @{
                                                if (nganchangiaitoa.LoaiVB.Equals(1))
                                                {
                                                    <b class="text-danger">Ngăn chặn</b>

                                                }
                                                else
                                                {
                                                    <b style="color:green;">Giải tỏa</b>
                                                }
                                            }

                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <input type="hidden" id="ncgtID" value="@nganchangiaitoa.ID" />
                        </td>

                        <td style="width:9%; z-index:1;">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class=" row justify-content-center">
                                        <div class="col-6 btn-group m-auto">
                                            <button class="btn btn-xs btn-outline-warning" onclick="btnGetSuancgtID(@nganchangiaitoa.ID);"><i class="fa fa-edit"></i></button>
                                        </div>
                                        <div class="col-6 btn-group m-auto">
                                            <button class="btn btn-xs btn-outline-danger" onclick="btnGetDeletencgt(@nganchangiaitoa.ID);"><i class="fa fa-trash"></i></button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </td>

                    </tr>

                }
            }
            else
            {
                @Html.Raw("Không có kết quả nào !")
            }
        }
    </tbody>

</table>
<div class="mailbox-controls">
    <!-- Check all button -->
    @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
            <i class="far fa-square"></i>
        </button>*@
    <!-- /.btn-group -->

    <div class="float-right">
        @Html.PagedListPager(Model, page => Url.Action("Search", "NganchanGiaitoa", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "tblncgt" }))
    </div>
    <!-- /.float-right -->


</div>

@*Trang @Model.PageNumber / @Model.PageCount*@

ccct2019/Views/NganchanGiaitoa/_ListNcgtMod.cshtml
@model IPagedList<NganchanGiaitoa>
@using ccct2019.Data
@using PagedList
@using PagedList.Mvc

<table class="table table-bordered table-responsive table-hover d-md-table table-head-fixed" style="overflow-x: scroll;">
    <thead class="text-dark" style="font-size:12px; font-family: Tahoma;">
        <tr class="text-center m-auto" style="z-index:9999999999; ">
            <th class="text-center text-white" style="width:3%; background-color:Highlight !important;">TT</th>
            <th class="text-center text-white" style="width:5%; background-color:Highlight !important;">SỐ GCN</th>
            <th class="text-center text-white" style="width:6%; background-color:Highlight !important;">NGÀY CẤP</th>
            <th class="text-center text-white" style="width:21%; background-color:Highlight !important;">NƠI CẤP</th>
            <th class="text-center text-white" style="width:10%; background-color:Highlight !important;">CHỦ SỞ HỮU</th>
            <th class="text-center text-white" style="width:6%; background-color:Highlight !important;">NGÀY VB</th>
            <th class="text-center text-white" style="width:52%; background-color:Highlight !important;">THÔNG TIN THỬA ĐẤT</th>
           
        </tr>

    </thead>
    <tbody class="" style="font-size:14px; ">
        @{
            int stt = 0;
            if (Model.Count() > 0)
            {
                foreach (var nganchangiaitoa in Model.OrderByDescending(x => x.CreateDate))
                {
                    stt++;
                    <tr ondblclick="btnGetXemncgtIDMod(@nganchangiaitoa.ID);" class="">
                        <th style="width:3%">@stt</th>
                        <td style="width:5%">@nganchangiaitoa.SoGCN</td>
                        <td style="width:6%">@(nganchangiaitoa.Ngaycap?.ToString("dd/MM/yyyy"))</td>
                        <td style="width:21%">@nganchangiaitoa.Noicap</td>
                        <td style="width:10%">
                            @nganchangiaitoa.Chusohuu

                        </td>

                        <td style="width:6%">@(nganchangiaitoa.NgayVB?.ToString("dd/MM/yyyy"))</td>
                        <td style="width:52%">
                            @*<div class="row">
                                    <div class="col-2 border-right"><b class="text-primary">Thửa đất số:</b> <b class="text-danger">@nganchangiaitoa.Thuadatso</b></div>
                                    <div class="col-2 border-right"><b class="text-primary">Bản đồ số:</b> <b class="text-danger">@nganchangiaitoa.Bandoso</b></div>
                                    <div class="col-5 border-right"><b class="text-primary">Địa chỉ:</b> <span class="">@nganchangiaitoa.Diachithuadat</span></div>
                                    <div class="col-3">
                                        Loại: @{
                                            if (nganchangiaitoa.LoaiVB.Equals(1))
                                            {
                                                <b style="color:red;"><i class="fa fa-stop-circle"></i> Ngăn chặn</b>
                                            }
                                            else
                                            {
                                                <b style="color:green;"><i class="fa fa-undo"></i> Giải tỏa</b>
                                            }
                                        }
                                    </div>
                                </div>*@
                            <table class="table table-condensed mb-0">
                                <thead>
                                    <tr class="text-sm-center bg-info">
                                        <td style="width:25%">Thửa đất</td>
                                        <td style="width:20%">Bản đồ</td>
                                        <td style="width:45%">Địa chỉ</td>
                                        <td style="width:10%">Loại</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="text-sm-center" style="font-size:12px;">
                                        <td style="width:15%"><b class="text-danger">@nganchangiaitoa.Thuadatso</b></td>
                                        <td style="width:10%"><b class="text-danger">@nganchangiaitoa.Bandoso</b></td>
                                        <td style="width:55%"><span>@nganchangiaitoa.Diachithuadat</span></td>
                                        <td style="width:20%">
                                            @{
                                                if (nganchangiaitoa.LoaiVB.Equals(1))
                                                {
                                                    <b class="text-danger">Ngăn chặn</b>

                                                }
                                                else
                                                {
                                                    <b style="color:green;">Giải tỏa</b>
                                                }
                                            }

                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <input type="hidden" id="ncgtID" value="@nganchangiaitoa.ID" />
                        </td>

                       

                    </tr>

                }
            }
            else
            {
                @Html.Raw("Không có kết quả nào !")
            }
        }
    </tbody>

</table>
<div class="mailbox-controls">
    <!-- Check all button -->
    @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
            <i class="far fa-square"></i>
        </button>*@
    <!-- /.btn-group -->

    <div class="float-right">
        @Html.PagedListPager(Model, page => Url.Action("SearchMod", "NganchanGiaitoa", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "tblncgtMod" }))
    </div>
    <!-- /.float-right -->


</div>

@*Trang @Model.PageNumber / @Model.PageCount*@

ccct2019/Views/NganchanGiaitoa/_Xoancgt.cshtml
@model ccct2019.Data.NganchanGiaitoa
<div class="modal fade m-auto" id="XoancgtModal" aria-hidden="true" style="display: none; width:20% !important; margin-top:10% !important; margin-left:40% !important;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Bạn có muốn xóa thông tin này không?</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body justify-content-center text-center">
                <input type="hidden" id="User" value="@Model.UserID" />
                <div class="row">
                    <div class="col">
                        <button type="button" class="btn btn-success btn-block" onclick="btnDeletencgt(@Model.ID);">Có</button>
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-outline-dark btn-block" data-dismiss="modal">Không</button>
                    </div>
                </div>


            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>